export enum AchievementType {
	HPRatio = "HPRatio",
	ArmorRatio = "ArmorRatio",
	TurnCount = "TurnCount",
	DeathCount = "DeathCount",
	MaxDamage = "MaxDamage",
	StoneCount = "StoneCount",
	GoldEraseCount = "GoldEraseCount",
	BlackEraseCount = "BlackEraseCount",
	WhiteEraseCount = "WhiteEraseCount",
	EraseCount = "EraseCount",
	BattleScore = "BattleScore",
	GoldSkillTagCount = "GoldSkillTagCount",
	BlackSkillTagCount = "BlackSkillTagCount",
	WhiteSkillTagCount = "WhiteSkillTagCount",
	SkillTagCount = "SkillTagCount",
	FriendBuffCount = "FriendBuffCount",
	EnemyBuffCount = "EnemyBuffCount",
	BuffCount = "BuffCount",
	GoldTriggerCount = "GoldTriggerCount",
	BlackTriggerCount = "BlackTriggerCount",
	WhiteTriggerCount = "WhiteTriggerCount",
	TriggerCount = "TriggerCount",
	KillCount = "KillCount",
	TotalDamage = "TotalDamage",
	Race = "Race",
}
