export enum GiveType {
	Coin = "Coin",
	Ring = "Ring",
	Soul = "Soul",
	DoNotUse = "DoNotUse",
	Medal = "Medal",
	GuildCoin = "GuildCoin",
	GuildRing = "GuildRing",
	PaidGem = "PaidGem",
	FreeGem = "FreeGem",
	Item = "Item",
	ExploreItem = "ExploreItem",
	IOSGem = "IOSGem",
	AndGem = "AndGem",
	DMMGem = "DMMGem",
	PlayerExp = "PlayerExp",
	Monster = "Monster",
	MonsterExp = "MonsterExp",
	HomeExp = "HomeExp",
	Decoration = "Decoration",
	Hero = "Hero",
	Diligent = "Diligent",
}
