export enum ItemCategory {
	None = 'None',
	Mineral = 'Mineral',
	Soul = 'Soul',
	Coin = 'Coin',
	PlayerExp = 'PlayerExp',
	HeroSkill = 'HeroSkill',
	WildcardMineral = 'WildcardMineral',
	Avatar = 'Avatar',
	Gem = 'Gem',
	Treasure = 'Treasure',
	GashaponTicket = 'GashaponTicket',
	Ring = 'Ring',
	WildcardOwnedAll = 'WildcardOwnedAll',
	WildcardOwnedGold = 'WildcardOwnedGold',
	WildcardOwnedBlack = 'WildcardOwnedBlack',
	WildcardOwnedWhite = 'WildcardOwnedWhite',
	HeroRank2 = 'HeroRank2',
	HeroRank3 = 'HeroRank3',
	HeroRank4 = 'HeroRank4',
	HeroRank5 = 'HeroRank5',
	Subscription = 'Subscription',
	Flag = 'Flag',
	Space = 'Space',
	Custom = 'Custom',
	Voucher = 'Voucher',
}
