name: "Assetbundle"

on:
  workflow_dispatch:

jobs:
  script:
    name: Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Checkout data
        uses: actions/checkout@v3
        with:
          ref: data
          path: data

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Create local changes
        timeout-minutes: 15
        run: npm run assetbundle
        env:
          NODE_ENV: production

      - uses: shallwefootball/s3-upload-action@v1.3.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'data/assetbundle/upload'
          destination_dir: ''

      - run: |
          cd data
          git pull --rebase --autostash

      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 更新Assetbundle資料 ${{ github.event.head_commit.sha }}
          repository: data
