name: "Data Process"

on:
  push:
    branches:
    - master
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  script:
    name: Script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout data
      uses: actions/checkout@v2
      with:
        ref: data
        path: data
        token: ${{ secrets.PAT }}

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Install Dependencies
      run: npm ci

    - name: Create local changes
      timeout-minutes: 15
      run: npm run script
      env:
        NODE_ENV: production

    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 更新資料 ${{ github.event.head_commit.sha }}
        repository: data
