name: "DialogAssets"

on:
  workflow_dispatch:

jobs:
  script:
    name: Script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Checkout data
      uses: actions/checkout@v2
      with:
        ref: data
        path: data

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm ci

    - name: Create local changes
      timeout-minutes: 15
      run: npm run dialog
      env:
        NODE_ENV: production

    - name: Commit files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 更新DialogAssets資料 ${{ github.event.head_commit.sha }}
        repository: data

    - name: Wiki Workflow Dispatch
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: Wiki
        token: ${{ secrets.PAT }}
